# Generated by Django 4.1.5 on 2024-03-19 19:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0002_redesocial_delete_socialnetwork"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RedeSocial",
            new_name="socialMedia",
        ),
        migrations.RenameField(
            model_name="socialmedia",
            old_name="icone",
            new_name="icon",
        ),
        migrations.RenameField(
            model_name="socialmedia",
            old_name="nome",
            new_name="prefix",
        ),
        migrations.RenameField(
            model_name="socialmedia",
            old_name="prefixo",
            new_name="socialMedia",
        ),
    ]
