# Generated by Django 4.1.5 on 2024-03-20 19:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0003_rename_redesocial_socialmedia_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmedia",
            name="icon",
            field=models.FileField(upload_to="static/icons/"),
        ),
    ]
