# Generated by Django 4.1.5 on 2024-03-21 17:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0005_rename_socialmedia_socialmedia_name_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="usernames",
            field=models.JSONField(default=list),
        ),
    ]
