# Generated by Django 4.1.5 on 2024-03-22 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("dashboard", "0007_usersocialmedia_delete_userprofile"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("job", models.CharField(blank=True, max_length=100)),
                ("is_student", models.BooleanField(default=False)),
                ("primary_color", models.CharField(blank=True, max_length=7)),
                ("secondary_color", models.CharField(blank=True, max_length=7)),
                ("font_color", models.CharField(blank=True, max_length=7)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
