# Generated by Django 4.1.5 on 2024-03-19 19:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RedeSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                ("prefixo", models.CharField(max_length=100)),
                ("icone", models.FileField(upload_to="icons/")),
            ],
        ),
        migrations.DeleteModel(
            name="SocialNetwork",
        ),
    ]
