# Generated by Django 4.1.5 on 2024-05-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0008_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersocialmedia",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="usersocialmedia",
            name="position",
            field=models.IntegerField(default=0),
        ),
    ]
