# Generated by Django 4.1.5 on 2024-03-18 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SocialMediaName", models.CharField(max_length=100)),
                ("urlPrefix", models.CharField(max_length=100)),
                ("svgIcon", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="UserProfileDefaults",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("PrimaryColor", models.CharField(max_length=7)),
                ("SecondaryColor", models.CharField(max_length=7)),
                (
                    "SocialMedias",
                    models.ManyToManyField(blank=True, to="accounts.socialmedia"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="social_networks",
        ),
        migrations.RemoveField(
            model_name="userprofile",
            name="user",
        ),
        migrations.DeleteModel(
            name="SocialNetwork",
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
