# Generated by Django 4.1.5 on 2024-03-18 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("accounts", "0002_socialmedia_userprofiledefaults_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("icon_svg", models.FileField(upload_to="icons/")),
                ("prefix", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("primary_color", models.CharField(max_length=7)),
                ("secondary_color", models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name="UserSocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                (
                    "social_network",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.socialnetwork",
                    ),
                ),
                (
                    "user_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.userprofile",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="userprofiledefaults",
            name="SocialMedias",
        ),
        migrations.RemoveField(
            model_name="userprofiledefaults",
            name="user",
        ),
        migrations.DeleteModel(
            name="SocialMedia",
        ),
        migrations.DeleteModel(
            name="UserProfileDefaults",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="social_networks",
            field=models.ManyToManyField(
                through="accounts.UserSocialNetwork", to="accounts.socialnetwork"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
